version: "3"

services:
  chibanode0:
    container_name: chibanode0
    image: "vulcanize/chiba-clonk:latest"
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "9090:9090"
      - "8545:8545"
      - "8546:8546"
      - "8125:8125"
    environment:
      - ID=0
      - LOG=${LOG:-ethermintd.log}
    volumes:
      - ./localnet-setup/node0/ethermintd:/ethermint:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.1

  chibanode1:
    container_name: chibanode1
    image: "vulcanize/chiba-clonk:latest"
    ports:
      - "26666-26667:26656-26657"
      - "1318:1317"
      - "9091:9090"
      - "8555:8545"
      - "8556:8546"
      - "8126:8125"
    environment:
      - ID=1
      - LOG=${LOG:-ethermintd.log}
    volumes:
      - ./localnet-setup/node1/ethermintd:/ethermint:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  chibanode2:
    container_name: chibanode2
    image: "vulcanize/chiba-clonk:latest"
    environment:
      - ID=2
      - LOG=${LOG:-ethermintd.log}
    ports:
      - "26676-26677:26656-26657"
      - "1319:1317"
      - "9092:9090"
      - "8565:8545"
      - "8566:8546"
      - "8127:8125"
    volumes:
      - ./localnet-setup/node2/ethermintd:/ethermint:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  chibanode3:
    container_name: chibanode3
    image: "vulcanize/chiba-clonk:latest"
    environment:
      - ID=3
      - LOG=${LOG:-ethermintd.log}
    ports:
      - "26686-26687:26656-26657"
      - "1320:1317"
      - "9093:9090"
      - "8575:8545"
      - "8576:8546"
      - "8128:8125"
    volumes:
      - ./localnet-setup/node3/ethermintd:/ethermint:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/16
